package de.eisi05.sql.statements.table;

import de.eisi05.sql.interfaces.SqlDataType;
import de.eisi05.sql.statements.where.AbstractWhereStatement;
import de.eisi05.sql.statements.where.WhereStatement;
import de.eisi05.sql.utils.OrmUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

public class TableColumn
{
    private final String name;
    private final SqlDataType<?> dataType;
    private final List<String> constraints = new ArrayList<>();
    private boolean isNotNull = false;
    private boolean isUnique = false;
    private boolean isPrimaryKey = false;
    private String check = null;
    private String defaultValue = null;
    private int[] autoIncrement = null;

    public TableColumn(String name, SqlDataType<?> dataType)
    {
        this.name = name;
        this.dataType = dataType;
    }

    public static TableColumn of(String name, SqlDataType<?> dataType)
    {
        return new TableColumn(name, dataType);
    }

    public TableColumn notNull()
    {
        isNotNull = true;
        return this;
    }

    public TableColumn unique()
    {
        isUnique = true;
        return this;
    }

    public TableColumn primaryKey()
    {
        isPrimaryKey = true;
        return this;
    }

    public TableColumn defaultValue(String defaultValue)
    {
        this.defaultValue = "DEFAULT (" + defaultValue + ")";
        return this;
    }

    public TableColumn setDefaultValue(String defaultValue)
    {
        this.defaultValue = "SET DEFAULT (" + defaultValue + ")";
        return this;
    }

    public TableColumn autoIncrement()
    {
        this.autoIncrement = new int[1];
        return this;
    }

    public TableColumn autoIncrement(int start, int increment)
    {
        this.autoIncrement = new int[]{start, increment};
        return this;
    }

    public TableColumn check(String key, Function<WhereStatement, AbstractWhereStatement> check)
    {
        this.check = check.apply(new WhereStatement(key)
        {
            @Override
            public String getKey()
            {
                return (logicOperator != null ? logicOperator.name() : "") + (withNot ? " NOT" : "");
            }
        }).getQuery();
        return this;
    }

    public TableColumn references(Class<?> table, String column)
    {
        constraints.add("REFERENCES " + OrmUtils.resolveTable(table) + "(" + column + ")");
        return this;
    }

    boolean isPrimaryKey()
    {
        return isPrimaryKey;
    }

    public String getName()
    {
        return name;
    }

    public SqlDataType<?> getDataType()
    {
        return dataType;
    }

    public String asQuery(boolean isPostgres)
    {
        StringBuilder sql = new StringBuilder();
        sql.append(name).append(" ").append(dataType.getName());

        if(autoIncrement != null && autoIncrement.length == 2)
            sql.append(" IDENTITY(").append(autoIncrement[0]).append(",").append(autoIncrement[1]).append(")");

        if(isNotNull)
            sql.append(" NOT NULL");
        if(isUnique)
            sql.append(" UNIQUE");

        boolean isPostgresIdentity = isPostgres && autoIncrement != null && autoIncrement.length < 2;
        if(defaultValue != null && !isPostgresIdentity)
            sql.append(" ").append(defaultValue.trim());

        if(autoIncrement != null && autoIncrement.length < 2)
        {
            if(isPostgres)
                sql.append(" GENERATED BY DEFAULT AS IDENTITY");
            else
                sql.append(" AUTO_INCREMENT");
        }

        if(isPrimaryKey)
            sql.append(" PRIMARY KEY");
        if(check != null)
            sql.append(" CHECK (").append(check).append(")");

        if(constraints != null && !constraints.isEmpty())
            sql.append(" ").append(String.join(" ", constraints));

        return sql.toString();
    }
}
